modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
[[mods]]
modId="pathtodirt"
version="${file.jarVersion}"
displayName="Path To Dirt"
displayURL="https://minecraft.curseforge.com/projects/path-to-dirt"
authors="Insane96MCP"
description='''
Simple mod that let you make Path from Dirt and Dirt from Path or Farmland
'''
[[dependencies.pathtodirt]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pathtodirt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"