modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
[[mods]]
modId="pathtodirt"
version="${file.jarVersion}"
displayName="Path To Dirt"
displayURL="https://minecraft.curseforge.com/projects/path-to-dirt"
authors="Insane96MCP"
description='''
Simple mod that let you transform Path and Farmland back to Dirt
'''
[[dependencies.pathtodirt]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pathtodirt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pathtodirt]]
    modId="insanelib"
    mandatory=true
    versionRange="[1.8.0,)"
    ordering="NONE"
    side="BOTH"